"""The Rust extension module. Mirrors `src/lib.rs`"""

from typing import Any

class Engine:
    def __init__(self, assets_dir: str) -> None: ...
    @property
    def context_is_live(self) -> bool: ...
    @property
    def learned_count(self) -> int: ...
    @property
    def learned_footprint(self) -> int: ...
    def best(self, word: str, prev: str | None) -> str: ...
    def analyze(self, word: str, prev: str | None) -> tuple[str, list[str]]: ...
    def candidates(self, word: str, prev: str | None) -> list[str]: ...
    def explain(self, word: str, prev: str | None) -> dict[str, Any]: ...
    def transliterate(self, text: str) -> str: ...
    def commit(self, roman: str, word: str, prev: str | None) -> None: ...
    def retract(self, roman: str, word: str, prev: str | None) -> None: ...
    def export_learned(self) -> bytes: ...
    def import_learned(self, data: bytes) -> bool: ...
    def clear_learned(self) -> None: ...
